version: '3.8'
services:

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ../frontend/:/app/result_build/

  db:
    image: postgres:13.0-alpine
    volumes:
      - foodgram_db:/var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    image: ika11ika/foodgram_strange:latest
    restart: always
    ports:
      - "8080:80"
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
      - data:/home/ika11ika/foodgram-project-react/data/
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:1.19.3
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - web

volumes:
  static_value:
  media_value:
  foodgram_db:
